export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_POKEDEX_SUCESS = 'FETCH_POKEDEX_SUCESS';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const CHANGE_POKEDEX = 'CHANGE_POKEDEX';
export const CHANGE_DISPLAY_TO = ' CHANGE_DISPLAY_TO';
export const FETCH_POKEDEX_START = 'FETCH_POKEDEX_START';
export const FETCH_POKEDEX_ERROR = 'FETCH_POKEDEX_ERROR';
