export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const CHANGE_POKEDEX = 'CHANGE_POKEDEX';
export const CHANGE_DISPLAY_TO = ' CHANGE_DISPLAY_TO';
